// Base de datos CCT — 506 registros (escuelas, supervisiones, jefaturas, subdirección)
// Generado automáticamente desde OTDE_Base_Contactos_v2.xlsx
// tipo: "escuela" | "supervision" | "jefatura" | "subdireccion"
// municipio: agregado desde "Catalogo SEPRN direcciones.xlsx" (18 municipios, columna "municip") — jul 2026

const CCT_DB = [
  {cct:'15DPR0432N',nombre:'Lic. Gabriel Ramos Millán',sector:'I',zona:1,tipo:'escuela',municipio:'Ayapango'},
  {cct:'15DPR0433M',nombre:'Cuauhtémoc',sector:'I',zona:1,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR0434L',nombre:'Redención Campesina',sector:'I',zona:1,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR0439G',nombre:'Niño Progresista',sector:'I',zona:1,tipo:'escuela',municipio:'Ayapango'},
  {cct:'15DPR0441V',nombre:'Insurgentes',sector:'I',zona:1,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR2933V',nombre:'Insurgentes',sector:'I',zona:1,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR3028Z',nombre:'Lic. Gabriel Ramos Millán',sector:'I',zona:1,tipo:'escuela',municipio:'Ayapango'},
  {cct:'15DPR0866Z',nombre:'Artículo 27 Constitucional',sector:'I',zona:2,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR0867Z',nombre:'Emiliano Zapata',sector:'I',zona:2,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR0868Y',nombre:'Lic. Benito Juárez',sector:'I',zona:2,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR0873J',nombre:'Gregorio Torres Quintero',sector:'I',zona:2,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR2237Y',nombre:'Melchor Ocampo',sector:'I',zona:2,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR0865A',nombre:'Cuauhtémoc',sector:'I',zona:3,tipo:'escuela',municipio:'Tenango del Aire'},
  {cct:'15DPR0869X',nombre:'Niños Héroes',sector:'I',zona:3,tipo:'escuela',municipio:'Tenango del Aire'},
  {cct:'15DPR0871L',nombre:'Diodoro C Olvera',sector:'I',zona:3,tipo:'escuela',municipio:'Tenango del Aire'},
  {cct:'15DPR0872K',nombre:'José María Morelos',sector:'I',zona:3,tipo:'escuela',municipio:'Tenango del Aire'},
  {cct:'15DPR0877F',nombre:'Confederación Nacional Campesina',sector:'I',zona:3,tipo:'escuela',municipio:'Temamatla'},
  {cct:'15DPR2766O',nombre:'Tenochtitlan',sector:'I',zona:3,tipo:'escuela',municipio:'Temamatla'},
  {cct:'15DPR2978R',nombre:'Confederación Nacional Campesina',sector:'I',zona:3,tipo:'escuela',municipio:'Temamatla'},
  {cct:'15DPR3005O',nombre:'Cuauhtémoc',sector:'I',zona:3,tipo:'escuela',municipio:'Tenango del Aire'},
  {cct:'15DPR0429Z',nombre:'Emiliano Zapata',sector:'I',zona:43,tipo:'escuela',municipio:'Atlautla'},
  {cct:'15DPR0430P',nombre:'Emancipación Campesina',sector:'I',zona:43,tipo:'escuela',municipio:'Atlautla'},
  {cct:'15DPR0435K',nombre:'Evolución Social',sector:'I',zona:43,tipo:'escuela',municipio:'Ozumba'},
  {cct:'15DPR0440W',nombre:'Miguel Hidalgo',sector:'I',zona:43,tipo:'escuela',municipio:'Ozumba'},
  {cct:'15DPR1300C',nombre:'Miguel Hidalgo y Costilla',sector:'I',zona:43,tipo:'escuela',municipio:'Atlautla'},
  {cct:'15DPR3077H',nombre:'Miguel Hidalgo',sector:'I',zona:43,tipo:'escuela',municipio:'Ozumba'},
  {cct:'15DPR0876G',nombre:'Francisco I Madero',sector:'I',zona:44,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR0878E',nombre:'Lic. Benito Juárez',sector:'I',zona:44,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR1525J',nombre:'Josefa Ortiz de Domínguez',sector:'I',zona:44,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR2946Z',nombre:'Francisco I Madero',sector:'I',zona:44,tipo:'escuela',municipio:'Tlalmanalco'},
  {cct:'15DPR0436J',nombre:'Cuauhtémoc',sector:'I',zona:56,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR0438H',nombre:'Lázaro Cárdenas',sector:'I',zona:56,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR1256F',nombre:'Dr. Belisario Domínguez',sector:'I',zona:56,tipo:'escuela',municipio:'Atlautla'},
  {cct:'15DPR1760N',nombre:'Niños Héroes',sector:'I',zona:56,tipo:'escuela',municipio:'Amecameca'},
  {cct:'15DPR2444F',nombre:'Emiliano Zapata',sector:'I',zona:56,tipo:'escuela',municipio:'Ayapango'},
  {cct:'15DPR0431O',nombre:'Presidente Benito Juárez',sector:'I',zona:70,tipo:'escuela',municipio:'Tepetlixpa'},
  {cct:'15DPR0437I',nombre:'Sor Juana I de la Cruz',sector:'I',zona:70,tipo:'escuela',municipio:'Tepetlixpa'},
  {cct:'15DPR0442U',nombre:'Narciso Mendoza',sector:'I',zona:70,tipo:'escuela',municipio:'Atlautla'},
  {cct:'15DPR0864B',nombre:'Gabino Barreda',sector:'I',zona:70,tipo:'escuela',municipio:'Juchitepec'},
  {cct:'15DPR0870M',nombre:'José Ma Morelos',sector:'I',zona:70,tipo:'escuela',municipio:'Juchitepec'},
  {cct:'15DPR1243B',nombre:'Justo Sierra',sector:'I',zona:70,tipo:'escuela',municipio:'Juchitepec'},
  {cct:'15DPR1436Q',nombre:'Sor Juana Inés de la Cruz',sector:'I',zona:70,tipo:'escuela',municipio:'Tepetlixpa'},
  {cct:'15DPR2236Z',nombre:'R Castellanos Figueroa',sector:'I',zona:70,tipo:'escuela',municipio:'Juchitepec'},
  {cct:'15DPR2979Q',nombre:'Presidente Benito Juárez',sector:'I',zona:70,tipo:'escuela',municipio:'Tepetlixpa'},
  {cct:'15DPR0456X',nombre:'José de la Mora',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0462H',nombre:'Profr Antonio Albarrán',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0465E',nombre:'Lic. Benito Juárez',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1666I',nombre:'Justo Sierra',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2613K',nombre:'Leona Vicario',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2704B',nombre:'Juana de Asbaje',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2937R',nombre:'Juana de Asbaje',sector:'II',zona:6,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0457W',nombre:'Profr Rafael Ramírez',sector:'II',zona:47,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0458V',nombre:'Lic. Benito Juárez',sector:'II',zona:47,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1670V',nombre:'Lic. Adolfo López Mateos',sector:'II',zona:47,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2612L',nombre:'Ignacio M Altamirano',sector:'II',zona:47,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2860T',nombre:'Moisés Sáenz',sector:'II',zona:47,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1623K',nombre:'Agustín Aragón y León',sector:'II',zona:48,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR1972Q',nombre:'Agustín Aragón y León',sector:'II',zona:48,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2222W',nombre:'Ignacio Zaragoza',sector:'II',zona:48,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2345F',nombre:'Emiliano Zapata Salazar',sector:'II',zona:48,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2615I',nombre:'Belisario Domínguez',sector:'II',zona:48,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2762S',nombre:'Miguel Hidalgo y Costilla',sector:'II',zona:48,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR1624J',nombre:'Sor Juana Inés de la Cruz',sector:'II',zona:49,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR1632S',nombre:'Nicolás Bravo',sector:'II',zona:49,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2340K',nombre:'Sor Juana Inés de la Cruz',sector:'II',zona:49,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2394O',nombre:'Ricardo Flores Magón',sector:'II',zona:49,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2610N',nombre:'Ricardo Flores Magón',sector:'II',zona:49,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2614J',nombre:'Hermenegildo Galeana',sector:'II',zona:49,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR3027Z',nombre:'Profr Delfino Pando Medina',sector:'II',zona:49,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0461I',nombre:'Vasco de Quiroga',sector:'II',zona:65,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1676P',nombre:'Vasco de Quiroga',sector:'II',zona:65,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1957Y',nombre:'Ludwig Van Beethoven',sector:'II',zona:65,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2611M',nombre:'Ludwig Van Beethoven',sector:'II',zona:65,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2749Y',nombre:'José Vasconcelos',sector:'II',zona:65,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR0893X',nombre:'Ignacio Allende',sector:'III',zona:12,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0895V',nombre:'Gral. Mariano Ruiz',sector:'III',zona:12,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0898S',nombre:'Gregorio Torres Quintero',sector:'III',zona:12,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1672T',nombre:'Vicente Guerrero',sector:'III',zona:12,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1807R',nombre:'Cuauhtémoc',sector:'III',zona:12,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR2370E',nombre:'Dr. Mariano G Somonte',sector:'III',zona:12,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0896U',nombre:'Ramón P Denegri',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0897T',nombre:'Venustiano Carranza',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0899R',nombre:'Gral. Manuel Ávila Camacho',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0900Q',nombre:'Profr German García Salgado',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0903N',nombre:'Centenario de la Reforma',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1776O',nombre:'Lic. Adolfo López Mateos',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR3134I',nombre:'Profr German García Salgado',sector:'III',zona:13,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0534K',nombre:'Benito Juárez',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0535J',nombre:'18 de Marzo',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0536I',nombre:'Miguel Hidalgo y Costilla',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0538G',nombre:'12 de Octubre',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0541U',nombre:'Netzahualcóyotl',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0543S',nombre:'Gral. Agustín Millán',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0545Q',nombre:'Gral. Ignacio Zaragoza',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1413F',nombre:'Gral. Vicente Guerrero',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1857Z',nombre:'Justo Sierra',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR2770A',nombre:'José María Luis Mora',sector:'III',zona:14,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0528Z',nombre:'Profr Carlos Inclán',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0537H',nombre:'Venustiano Carranza',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0539F',nombre:'Francisco I Madero',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0540V',nombre:'Gral. Vicente Guerrero',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0542T',nombre:'Vicente Riva Palacio',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0544R',nombre:'Melchor Ocampo',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR2238X',nombre:'Profr Carlos Inclán',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR2245G',nombre:'Lázaro Cárdenas',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR2819C',nombre:'Manuel Doblado',sector:'III',zona:15,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0530O',nombre:'Ma Trinidad Rodríguez de Sánchez Colin',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0532M',nombre:'Fray Pedro de Gante',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0533L',nombre:'Francisco I Madero',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0901P',nombre:'Gral. José Ma Morelos y Pavón',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1076V',nombre:'Melchor Ocampo',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1855A',nombre:'Carmen Serdán',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR1923H',nombre:'Gilberto Palacios de la Rosa',sector:'III',zona:54,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0527A',nombre:'Profr Justo Sierra',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0529Z',nombre:'Benito Juárez',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0531N',nombre:'Miguel Hidalgo',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0546P',nombre:'Guadalupe Borja de Díaz Ordaz',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0550B',nombre:'Fray Pedro de Gante',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0551A',nombre:'Francisco I Madero',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0560I',nombre:'Miguel Hidalgo',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0561H',nombre:'Gral. Ignacio Zaragoza',sector:'III',zona:55,tipo:'escuela',municipio:'Texcoco'},
  {cct:'15DPR0793Y',nombre:'Leyes de Reforma',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR0794X',nombre:'Artículo 3o Constitucional',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1022R',nombre:'Ignacio Manuel Altamirano',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1301B',nombre:'Ignacio Manuel Altamirano',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1532T',nombre:'Lic. Benito Juárez',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR2188F',nombre:'Niños Héroes',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR2673Z',nombre:'México',sector:'IV',zona:8,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR0336K',nombre:'Lic. Adolfo López Mateos',sector:'IV',zona:9,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR0795W',nombre:'Gral. Lázaro Cárdenas',sector:'IV',zona:9,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR0797U',nombre:'José Ma Morelos',sector:'IV',zona:9,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1785W',nombre:'Gral. Francisco Villa',sector:'IV',zona:9,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1885V',nombre:'Pedro Moreno',sector:'IV',zona:9,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1898Z',nombre:'Gregorio Torres Quintero',sector:'IV',zona:9,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR0894W',nombre:'Benito Juárez',sector:'IV',zona:10,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR1254H',nombre:'Belisario Domínguez',sector:'IV',zona:10,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR1673S',nombre:'Emiliano Zapata',sector:'IV',zona:10,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR2247E',nombre:'Valentín Gómez Farias',sector:'IV',zona:10,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR3119Q',nombre:'Profr Mario Rojas Aguilar',sector:'IV',zona:10,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR0023J',nombre:'Narciso Mendoza',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0819P',nombre:'Francisco Sarabia',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1420P',nombre:'Xicoténcatl',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1445Y',nombre:'Ricardo Flores Magón',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1781Z',nombre:'Héroes de la Independencia',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1966F',nombre:'Netzahualcóyotl',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2810L',nombre:'Mohandas Karamchand Gandhi',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2905Z',nombre:'Mohandas Karamchand Gandhi',sector:'IV',zona:52,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0821D',nombre:'Adolfo Ruiz Cortines',sector:'IV',zona:60,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR1583Z',nombre:'Vicente Guerrero',sector:'IV',zona:60,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR3000T',nombre:'Profr Rafael Ramírez Castañeda',sector:'IV',zona:60,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR3234H',nombre:'Profr Rafael Ramírez Castañeda',sector:'IV',zona:60,tipo:'escuela',municipio:'La Paz'},
  {cct:'15DPR0902O',nombre:'Juan Escutia',sector:'IV',zona:66,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR1667H',nombre:'Gral. Lázaro Cárdenas del Rio',sector:'IV',zona:66,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR1829C',nombre:'Ejercito del Trabajo',sector:'IV',zona:66,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR1899Y',nombre:'Gral. Ignacio Zaragoza',sector:'IV',zona:66,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR2601F',nombre:'Venustiano Carranza',sector:'IV',zona:66,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR0471P',nombre:'Víctor Manuel Villaseñor Moore',sector:'V',zona:16,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0473N',nombre:'Justo Sierra Méndez',sector:'V',zona:16,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0477J',nombre:'Felipe Carrillo Puerto',sector:'V',zona:16,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1612E',nombre:'Antonio Barbosa Heldt',sector:'V',zona:16,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2419G',nombre:'Rosario Castellanos',sector:'V',zona:16,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0469A',nombre:'Pdte. Benito Juárez',sector:'V',zona:17,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0474M',nombre:'Libertador Miguel Hidalgo',sector:'V',zona:17,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1258D',nombre:'Lázaro Cárdenas',sector:'V',zona:17,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1482B',nombre:'Tamaulipas',sector:'V',zona:17,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1487X',nombre:'Liberación',sector:'V',zona:17,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1613D',nombre:'Emiliano Zapata',sector:'V',zona:17,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0468B',nombre:'Melchor Ocampo',sector:'V',zona:18,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0476K',nombre:'Lic. Adolfo López Mateos',sector:'V',zona:18,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1636O',nombre:'Vicente Guerrero',sector:'V',zona:18,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2429N',nombre:'Alfonso Reyes',sector:'V',zona:18,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0467C',nombre:'Cuauhtémoc',sector:'V',zona:19,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0472O',nombre:'Hermenegildo Galeana',sector:'V',zona:19,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1565K',nombre:'Ángel Albino Corzo',sector:'V',zona:19,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2519F',nombre:'18 de Marzo',sector:'V',zona:19,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0292D',nombre:'Gral. Ignacio Zaragoza',sector:'V',zona:24,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0481W',nombre:'Lic. Adolfo López Mateos',sector:'V',zona:24,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0483U',nombre:'Lic. Adolfo López Mateos',sector:'V',zona:24,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1260S',nombre:'Profr Pablo Lorenzana Rubín',sector:'V',zona:24,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0479H',nombre:'Francisco González Bocanegra',sector:'V',zona:57,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0482V',nombre:'Francisco González Bocanegra',sector:'V',zona:57,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1375T',nombre:'Gral. Ignacio Mejía',sector:'V',zona:57,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2578V',nombre:'Gral. Vicente Guerrero',sector:'V',zona:57,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0485S',nombre:'Miguel Hidalgo y Costilla',sector:'V',zona:64,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0486R',nombre:'Lic. Benito Juárez',sector:'V',zona:64,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2746A',nombre:'Miguel Hidalgo y Costilla',sector:'V',zona:64,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0484T',nombre:'José Ma Morelos y Pavón',sector:'VI',zona:27,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0487Q',nombre:'Ma Enriqueta Camarillo y Roa',sector:'VI',zona:27,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0488P',nombre:'Profr Rafael Ramírez',sector:'VI',zona:27,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1262Q',nombre:'Ricardo Flores Magón',sector:'VI',zona:27,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1439N',nombre:'José Antonio Alzate',sector:'VI',zona:27,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0522F',nombre:'Miguel Hidalgo y Costilla',sector:'VI',zona:30,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0526B',nombre:'Gral. Lázaro Cárdenas del Rio',sector:'VI',zona:30,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1263P',nombre:'Valentín Gómez Farias',sector:'VI',zona:30,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1264O',nombre:'Lic. Benito Juárez García',sector:'VI',zona:30,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1368J',nombre:'Profr Mario Rojas Aguilar',sector:'VI',zona:30,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1369I',nombre:'Emiliano Zapata',sector:'VI',zona:30,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0504Q',nombre:'Gral. Don Juan Álvarez',sector:'VI',zona:31,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0507N',nombre:'Gral. Vicente Guerrero',sector:'VI',zona:31,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0860F',nombre:'Agustín Melgar',sector:'VI',zona:31,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0861E',nombre:'Constitución de 1857',sector:'VI',zona:31,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1253I',nombre:'Lic. Benito Juárez',sector:'VI',zona:31,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1533S',nombre:'Ramón López Velarde',sector:'VI',zona:31,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0506O',nombre:'Narciso Mendoza',sector:'VI',zona:32,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0859Q',nombre:'Lic. Adolfo López Mateos',sector:'VI',zona:32,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1531U',nombre:'Miguel Hidalgo y Costilla',sector:'VI',zona:32,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0492B',nombre:'Cuauhtémoc',sector:'VI',zona:33,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0493A',nombre:'Damián Carmona',sector:'VI',zona:33,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0495Z',nombre:'Mariano Matamoros',sector:'VI',zona:33,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0497X',nombre:'Damián Carmona',sector:'VI',zona:33,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0498W',nombre:'Cuauhtémoc',sector:'VI',zona:33,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0494Z',nombre:'Niños Héroes de Chapultepec',sector:'VI',zona:34,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0496Y',nombre:'Niños Héroes de Chapultepec',sector:'VI',zona:34,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0500U',nombre:'Belisario Domínguez',sector:'VI',zona:34,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0503R',nombre:'Ignacio Manuel Altamirano',sector:'VI',zona:34,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0505P',nombre:'Justo Sierra Méndez',sector:'VI',zona:34,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0512Z',nombre:'Melchor Ocampo',sector:'VII',zona:37,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0513Y',nombre:'Ignacio Allende Unzaga',sector:'VII',zona:37,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0514X',nombre:'Profr Carlos Hank González',sector:'VII',zona:37,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1650H',nombre:'Ignacio Allende Unzaga',sector:'VII',zona:37,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1734P',nombre:'Lic. José López Portillo y Rojas',sector:'VII',zona:37,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0854V',nombre:'Netzahualcóyotl',sector:'VII',zona:38,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1117E',nombre:'Constitución de 1857',sector:'VII',zona:38,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1416C',nombre:'Tamaulipas',sector:'VII',zona:38,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1524K',nombre:'Gral. Lázaro Cárdenas del Rio',sector:'VII',zona:38,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2298L',nombre:'Profra Aurelia Rico Gómez',sector:'VII',zona:38,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0519S',nombre:'Guadalupe Victoria',sector:'VII',zona:39,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0523E',nombre:'Guadalupe Victoria',sector:'VII',zona:39,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1827E',nombre:'Alfonso Reyes',sector:'VII',zona:39,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2466R',nombre:'Alfonso Reyes',sector:'VII',zona:39,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0509L',nombre:'Revolución Mexicana',sector:'VII',zona:61,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0510A',nombre:'Benito Juárez',sector:'VII',zona:61,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0511Z',nombre:'Francisco I Madero',sector:'VII',zona:61,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0518T',nombre:'Francisco I Madero',sector:'VII',zona:61,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0520H',nombre:'Isidro Fabela',sector:'VII',zona:63,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0524D',nombre:'Isidro Fabela',sector:'VII',zona:63,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0852X',nombre:'Rafael Ramírez',sector:'VII',zona:63,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0853W',nombre:'Triunfo de la República',sector:'VII',zona:63,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0857S',nombre:'Triunfo de la República',sector:'VII',zona:63,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1419Z',nombre:'Niños Héroes',sector:'VII',zona:63,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0182Y',nombre:'Niño Artillero',sector:'VIII',zona:4,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR0222I',nombre:'José Ma Morelos y Pavón',sector:'VIII',zona:4,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR0444S',nombre:'Tierra y Libertad',sector:'VIII',zona:4,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR1435R',nombre:'Emiliano Zapata',sector:'VIII',zona:4,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR0445R',nombre:'Profr Rafael M Navas',sector:'VIII',zona:42,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR1647U',nombre:'Gral. Lázaro Cárdenas',sector:'VIII',zona:42,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR1864I',nombre:'Sor Juana Inés de la Cruz',sector:'VIII',zona:42,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR2598I',nombre:'Francisco I Madero',sector:'VIII',zona:42,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0180Z',nombre:'Juan Escutia',sector:'VIII',zona:45,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0447P',nombre:'Ing. Rafael García Moreno',sector:'VIII',zona:45,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0451B',nombre:'José Vicente Villada',sector:'VIII',zona:45,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0455Y',nombre:'Ignacio Zaragoza',sector:'VIII',zona:45,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0874I',nombre:'Miguel Hidalgo',sector:'VIII',zona:45,tipo:'escuela',municipio:'Temamatla'},
  {cct:'15DPR2240L',nombre:'Profr Otilio Montaño',sector:'VIII',zona:45,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR2405D',nombre:'Fray Martín de Valencia',sector:'VIII',zona:45,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0454Z',nombre:'Vicente Guerrero',sector:'VIII',zona:46,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0875H',nombre:'18 de Marzo',sector:'VIII',zona:46,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR1242C',nombre:'Lic. Adolfo López Mateos',sector:'VIII',zona:46,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR1866G',nombre:'Guadalupe Victoria',sector:'VIII',zona:46,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3298S',nombre:'Josefa Ortiz de Domínguez',sector:'VIII',zona:46,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0449N',nombre:'Wenceslao Labra',sector:'VIII',zona:62,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR1838K',nombre:'21 de Marzo',sector:'VIII',zona:62,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR1856Z',nombre:'21 de Marzo',sector:'VIII',zona:62,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR3256T',nombre:'Octavio Paz',sector:'VIII',zona:62,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0231Q',nombre:'Cristóbal Colón',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0446Q',nombre:'Pedro León',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0452A',nombre:'Anáhuac',sector:'VIII',zona:69,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR0453Z',nombre:'Benito Juárez',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR2855H',nombre:'Carlos Chávez',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR2893K',nombre:'Cuauhtémoc',sector:'VIII',zona:69,tipo:'escuela',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15DPR2915F',nombre:'Cristóbal Colón',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR2943B',nombre:'Carlos Chávez',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3162E',nombre:'Benito Juárez',sector:'VIII',zona:69,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3270M',nombre:'Rosario Castellanos',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3289K',nombre:'Laura Méndez de Cuenca',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3290Z',nombre:'Diego Rivera',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3299R',nombre:'Carlos Fuentes',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3308I',nombre:'José Emilio Pacheco',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3317Q',nombre:'José Emilio Pacheco',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3318P',nombre:'Carlos Fuentes',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3320D',nombre:'Ma Petra Arreola Echeverria',sector:'VIII',zona:73,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0311B',nombre:'José María Morelos y Pavón',sector:'IX',zona:25,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0842Q',nombre:'Ignacio Allende',sector:'IX',zona:25,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1070A',nombre:'Estado de México',sector:'IX',zona:25,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0489O',nombre:'Gral. Francisco Villa',sector:'IX',zona:26,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1261R',nombre:'Netzahualcóyotl',sector:'IX',zona:26,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2748Z',nombre:'Adolfo López Mateos',sector:'IX',zona:26,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0846M',nombre:'Melchor Ocampo',sector:'IX',zona:28,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0848K',nombre:'Ignacio Allende',sector:'IX',zona:28,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1305Y',nombre:'Educación y Patria',sector:'IX',zona:28,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0844O',nombre:'Aquiles Serdán',sector:'IX',zona:58,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0847L',nombre:'Ignacio Manuel Altamirano',sector:'IX',zona:58,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0851Y',nombre:'Gral. Lázaro Cárdenas',sector:'IX',zona:58,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1639L',nombre:'Alfredo V Bonfil Pinto',sector:'IX',zona:58,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0508M',nombre:'Don Aquiles Serdán',sector:'IX',zona:59,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0845N',nombre:'Venustiano Carranza',sector:'IX',zona:59,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0849J',nombre:'Dr. José Ma Luis Mora',sector:'IX',zona:59,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1479O',nombre:'Héroes de Zacapoaxtla',sector:'IX',zona:59,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1534R',nombre:'Ignacio Zaragoza',sector:'IX',zona:59,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1627G',nombre:'Francisco Javier Mina',sector:'X',zona:35,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1665J',nombre:'Lic. Alfredo V Bonfil',sector:'X',zona:35,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2542G',nombre:'Profr Simón Ramírez Rodríguez',sector:'X',zona:35,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2917D',nombre:'Japón',sector:'X',zona:35,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0521G',nombre:'Benemérito de las Américas',sector:'X',zona:36,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0525C',nombre:'Valentín Gómez Farias',sector:'X',zona:36,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1265N',nombre:'Ricardo Flores Magón',sector:'X',zona:36,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1542Z',nombre:'Edmundo Tortoledo Covarrubias',sector:'X',zona:36,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0757T',nombre:'Año de la Patria',sector:'X',zona:40,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0760G',nombre:'Netzahualcóyotl',sector:'X',zona:40,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0773K',nombre:'Vicente Guerrero',sector:'X',zona:40,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1834O',nombre:'David G Berlanga',sector:'X',zona:40,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2299K',nombre:'Nueva Escocia',sector:'X',zona:40,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0369B',nombre:'Cuitláhuac',sector:'X',zona:41,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1250L',nombre:'Amado Nervo',sector:'X',zona:41,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1463N',nombre:'Juan Escutia',sector:'X',zona:41,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1744W',nombre:'Laura Méndez de Cuenca',sector:'X',zona:41,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0758S',nombre:'Calmécac',sector:'X',zona:68,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0761F',nombre:'Lic. Adolfo López Mateos',sector:'X',zona:68,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1307W',nombre:'Gral. Lázaro Cárdenas',sector:'X',zona:68,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1433T',nombre:'Gral. Francisco Villa',sector:'X',zona:68,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1740Z',nombre:'Profe Ildefonso Velázquez Ibarra',sector:'X',zona:68,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2451P',nombre:'Insurgente Hermenegildo Galeana',sector:'X',zona:68,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0798T',nombre:'Emiliano Zapata',sector:'XI',zona:11,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1969C',nombre:'Lázaro Cárdenas',sector:'XI',zona:11,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2703C',nombre:'Ciudad de México',sector:'XI',zona:11,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2866N',nombre:'Hermenegildo Galeana',sector:'XI',zona:11,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2977S',nombre:'Hermenegildo Galeana',sector:'XI',zona:11,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR3160G',nombre:'Profr Gregorio Torres Quintero',sector:'XI',zona:11,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR3235G',nombre:'Profr Gregorio Torres Quintero',sector:'XI',zona:11,tipo:'escuela',municipio:'Chicoloapan'},
  {cct:'15DPR0170T',nombre:'Estado de Morelos',sector:'XI',zona:51,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1867F',nombre:'Jesús Urueta',sector:'XI',zona:51,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2865O',nombre:'Moisés Sáenz Garza',sector:'XI',zona:51,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2878S',nombre:'Moisés Sáenz Garza',sector:'XI',zona:51,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0822C',nombre:'Venustiano Carranza',sector:'XI',zona:53,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0823B',nombre:'Constitución y Reforma',sector:'XI',zona:53,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1535Q',nombre:'Tierra y Libertad',sector:'XI',zona:53,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2447C',nombre:'Ignacio Zaragoza',sector:'XI',zona:53,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR3023D',nombre:'15 de Septiembre',sector:'XI',zona:53,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0820E',nombre:'Dr. Gustavo Baz',sector:'XI',zona:67,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1347X',nombre:'Aquiles Serdán',sector:'XI',zona:67,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1442A',nombre:'José Ma Pino Suarez',sector:'XI',zona:67,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1959W',nombre:'Tenochtitlan',sector:'XI',zona:67,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1964H',nombre:'Juana Inés de Asbaje',sector:'XI',zona:67,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2225T',nombre:'Rafael Ramírez Castañeda',sector:'XI',zona:67,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1443Z',nombre:'Nacionalización Bancaria',sector:'XI',zona:71,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR1444Z',nombre:'Niños Héroes de Chapultepec',sector:'XI',zona:71,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2420W',nombre:'Vidal Alcocer',sector:'XI',zona:71,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2932W',nombre:'Vidal Alcocer',sector:'XI',zona:71,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0022K',nombre:'Justo Sierra',sector:'XI',zona:72,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0818Q',nombre:'Justo Sierra',sector:'XI',zona:72,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2272D',nombre:'Acamapichtli',sector:'XI',zona:72,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2343H',nombre:'Ignacio Manuel Altamirano',sector:'XI',zona:72,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR2360Y',nombre:'Otilio Montaño',sector:'XI',zona:72,tipo:'escuela',municipio:'Chimalhuacán'},
  {cct:'15DPR0470Q',nombre:'Antonio Caso',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0475L',nombre:'Lic. José Ma Pino Suarez',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1081G',nombre:'Mtro. Baldomero Mendoza Ochoa',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1560P',nombre:'Amado Nervo',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1610G',nombre:'Ricardo Flores Magón',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1611F',nombre:'Ricardo Flores Magón',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1696C',nombre:'Dr. Gustavo Baz Prada',sector:'XII',zona:20,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0028E',nombre:'Lázaro Cárdenas',sector:'XII',zona:21,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0315Y',nombre:'Lic. Benito Juárez',sector:'XII',zona:21,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0316X',nombre:'Lic. Benito Juárez',sector:'XII',zona:21,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1259C',nombre:'Severiano Gómez Ontiveros',sector:'XII',zona:21,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1371X',nombre:'Gregorio Torres Quintero',sector:'XII',zona:21,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1372W',nombre:'Gregorio Torres Quintero',sector:'XII',zona:21,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0480X',nombre:'Emiliano Zapata',sector:'XII',zona:22,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1446X',nombre:'Alfonso García Robles',sector:'XII',zona:22,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1449U',nombre:'Octavio Paz',sector:'XII',zona:22,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0843P',nombre:'Pdte. Adolfo López Mateos',sector:'XII',zona:23,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1733Q',nombre:'Estado de Michoacán',sector:'XII',zona:23,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR1944U',nombre:'Constitución de Apatzingán',sector:'XII',zona:23,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR2581I',nombre:'Ricardo Flores Magón',sector:'XII',zona:23,tipo:'escuela',municipio:'Nezahualcóyotl'},
  {cct:'15DPR0077N',nombre:'Héroes de la Libertad',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0080A',nombre:'Héroes de la Libertad',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0443T',nombre:'Benito Juárez',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0448O',nombre:'Niño Artillero',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR1725H',nombre:'Lic. Adolfo López Mateos',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3286N',nombre:'Niños Héroes',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3287M',nombre:'Frida Kahlo',sector:'XIII',zona:5,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0464F',nombre:'Venustiano Carranza',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2864P',nombre:'Etucuaro',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3030N',nombre:'Profr Juan de Dios Rodríguez Heredia',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3044Q',nombre:'Cuauhtémoc',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3045P',nombre:'Profr Ernesto Guajardo Salinas',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3063E',nombre:'Profr Néstor Membrillo Díaz',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3076I',nombre:'Profr Néstor Membrillo Díaz',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3166A',nombre:'José Vasconcelos',sector:'XIII',zona:7,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0450C',nombre:'Profr Eduardo Mendieta',sector:'XIII',zona:29,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR2235Z',nombre:'José Ma Morelos y Pavón',sector:'XIII',zona:29,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3189L',nombre:'Francisco Villa',sector:'XIII',zona:29,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3190A',nombre:'Carlos Monsiváis',sector:'XIII',zona:29,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3253W',nombre:'Cuitláhuac',sector:'XIII',zona:29,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3274I',nombre:'Cuitláhuac',sector:'XIII',zona:29,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3321C',nombre:'José Carbajal García',sector:'XIII',zona:29,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0063K',nombre:'Juan Rulfo',sector:'XIII',zona:50,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0463G',nombre:'Gabriel Leyva Solano',sector:'XIII',zona:50,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0466D',nombre:'Gral. Lázaro Cárdenas',sector:'XIII',zona:50,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1471W',nombre:'Hermanos Serdán',sector:'XIII',zona:50,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2935T',nombre:'Juan Rulfo',sector:'XIII',zona:50,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3276G',nombre:'Felipe Santiago Xicoténcatl',sector:'XIII',zona:50,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR3288L',nombre:'Felipe Santiago Xicoténcatl',sector:'XIII',zona:50,tipo:'escuela',municipio:'Chalco'},
  {cct:'15DPR0006T',nombre:'Lic. Justo Sierra Méndez',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0459U',nombre:'20 de Noviembre',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR0460J',nombre:'Francisco I Madero',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1584Z',nombre:'Andrés Molina Enríquez',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR1675Q',nombre:'Miguel Hidalgo',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR2709X',nombre:'Simón Ramírez Rodríguez',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3157T',nombre:'Profr Silvino Berna Olivar',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3213V',nombre:'Profr Silvino Berna Olivar',sector:'XIII',zona:74,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3080V',nombre:'Profra María Lavalle Urbina',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3081U',nombre:'Profr Rodrigo Morales Cruz',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3082T',nombre:'Profr Rodrigo Morales Cruz',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3083S',nombre:'Profra María Lavalle Urbina',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3091A',nombre:'Profra Yolanda Cuervo Toledano',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3092Z',nombre:'Gregorio Torres Quintero',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15DPR3114V',nombre:'Profra Yolanda Cuervo Toledano',sector:'XIII',zona:75,tipo:'escuela',municipio:'Ixtapaluca'},
  {cct:'15FIZ0042V',nombre:'Supervisión Escolar N. 1',sector:'I',zona:1,tipo:'supervision',municipio:'Amecameca'},
  {cct:'15FIZ0043U',nombre:'Supervisión Escolar N. 2',sector:'I',zona:2,tipo:'supervision',municipio:'Tlalmanalco'},
  {cct:'15FIZ0044T',nombre:'Supervisión Escolar N. 3',sector:'I',zona:3,tipo:'supervision',municipio:'Tenango del Aire'},
  {cct:'15FIZ0045S',nombre:'Supervisión Escolar N.04',sector:'VIII',zona:4,tipo:'supervision',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15FIZ0046R',nombre:'Supervisión Escolar N. 5',sector:'XIII',zona:5,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0047Q',nombre:'Supervisión Escolar N. 06',sector:'II',zona:6,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FIZ0048P',nombre:'Supervisión Escolar N. 7',sector:'XIII',zona:7,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FIZ0049O',nombre:'Supervisión Escolar N. 8',sector:'IV',zona:8,tipo:'supervision',municipio:'La Paz'},
  {cct:'15FIZ0050D',nombre:'Supervisión Escolar N. 9',sector:'IV',zona:9,tipo:'supervision',municipio:'La Paz'},
  {cct:'15FIZ0051C',nombre:'Supervisión Escolar N. 10',sector:'IV',zona:10,tipo:'supervision',municipio:'Chicoloapan'},
  {cct:'15FIZ0052B',nombre:'Supervisión Escolar N. 11',sector:'XI',zona:11,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0053A',nombre:'Supervisión Escolar N. 12',sector:'III',zona:12,tipo:'supervision',municipio:'Texcoco'},
  {cct:'15FIZ0054Z',nombre:'Supervisión Escolar N. 13',sector:'III',zona:13,tipo:'supervision',municipio:'Texcoco'},
  {cct:'15FIZ0055Z',nombre:'Supervisión Escolar N. 14',sector:'III',zona:14,tipo:'supervision',municipio:'Texcoco'},
  {cct:'15FIZ0056Y',nombre:'Supervisión Escolar N. 15',sector:'III',zona:15,tipo:'supervision',municipio:'Texcoco'},
  {cct:'15FIZ0057X',nombre:'Supervisión Escolar N. 16',sector:'V',zona:16,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0058W',nombre:'Supervisión Escolar N. 17',sector:'V',zona:17,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0059V',nombre:'Supervisión Escolar N. 18',sector:'V',zona:18,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0060K',nombre:'Supervisión Escolar N. 19',sector:'V',zona:19,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0061J',nombre:'Supervisión Escolar N. 20',sector:'XII',zona:20,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0062I',nombre:'Supervisión Escolar N. 21',sector:'XII',zona:21,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0063H',nombre:'Supervisión Escolar N. 22',sector:'XII',zona:22,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0064G',nombre:'Supervisión Escolar N. 23',sector:'XII',zona:23,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0065F',nombre:'Supervisión Escolar N. 24',sector:'V',zona:24,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0066E',nombre:'Supervisión Escolar N. 25',sector:'IX',zona:25,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0067D',nombre:'Supervisión Escolar N. 26',sector:'IX',zona:26,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0068C',nombre:'Supervisión Escolar N. 27',sector:'VI',zona:27,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0069B',nombre:'Supervisión Escolar N. 28',sector:'IX',zona:28,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0070R',nombre:'Supervisión Escolar N. 29',sector:'XIII',zona:29,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0071Q',nombre:'Supervisión Escolar N. 30',sector:'VI',zona:30,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0072P',nombre:'Supervisión Escolar N. 31',sector:'VI',zona:31,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0073O',nombre:'Supervisión Escolar N. 32',sector:'VI',zona:32,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0074N',nombre:'Supervisión Escolar N. 33',sector:'VI',zona:33,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0075M',nombre:'Supervisión Escolar N. 34',sector:'VI',zona:34,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0076L',nombre:'Supervisión Escolar N. 35',sector:'X',zona:35,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0077K',nombre:'Supervisión Escolar N. 36',sector:'X',zona:36,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0078J',nombre:'Supervisión Escolar N. 37',sector:'VII',zona:37,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0079I',nombre:'Supervisión Escolar N. 38',sector:'VII',zona:38,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0080Y',nombre:'Supervisión Escolar N. 39',sector:'VII',zona:39,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0081X',nombre:'Supervisión Escolar N. 40',sector:'X',zona:40,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0082W',nombre:'Supervisión Escolar N. 41',sector:'X',zona:41,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0083V',nombre:'Supervisión Escolar N. 42',sector:'VIII',zona:42,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0258U',nombre:'Supervisión Escolar N. 43',sector:'I',zona:43,tipo:'supervision',municipio:'Ozumba'},
  {cct:'15FIZ0219S',nombre:'Supervisión Escolar N. 44',sector:'I',zona:44,tipo:'supervision',municipio:'Tlalmanalco'},
  {cct:'15FIZ0220H',nombre:'Supervisión Escolar N. 45',sector:'VIII',zona:45,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0221G',nombre:'Supervisión Escolar N. 46',sector:'VIII',zona:46,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0222F',nombre:'Supervisión Escolar N. 47',sector:'II',zona:47,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FIZ0249M',nombre:'Supervisión Escolar N. 48',sector:'II',zona:48,tipo:'supervision',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15FIZ0250B',nombre:'Supervisión Escolar N. 49',sector:'II',zona:49,tipo:'supervision',municipio:'Valle de Chalco Solidaridad'},
  {cct:'15FIZ0223E',nombre:'Supervisión Escolar N. 50',sector:'XIII',zona:50,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FIZ0224D',nombre:'Supervisión Escolar N. 51',sector:'XI',zona:51,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0225C',nombre:'Supervisión Escolar N. 52',sector:'IV',zona:52,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0226B',nombre:'Supervisión Escolar N. 53',sector:'XI',zona:53,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0251A',nombre:'Supervisión Escolar N. 54',sector:'III',zona:54,tipo:'supervision',municipio:'Texcoco'},
  {cct:'15FIZ0252Z',nombre:'Supervisión Escolar N. 55',sector:'III',zona:55,tipo:'supervision',municipio:'Texcoco'},
  {cct:'15FIZ0253Z',nombre:'Supervisión Escolar N. 56',sector:'I',zona:56,tipo:'supervision',municipio:'Atlautla'},
  {cct:'15FIZ0227A',nombre:'Supervisión Escolar N. 57',sector:'V',zona:57,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0254Y',nombre:'Supervisión Escolar N. 58',sector:'IX',zona:58,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0228Z',nombre:'Supervisión Escolar N. 59',sector:'IX',zona:59,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0229Z',nombre:'Supervisión Escolar N. 60',sector:'IV',zona:60,tipo:'supervision',municipio:'La Paz'},
  {cct:'15FIZ0255X',nombre:'Supervisión Escolar N. 61',sector:'VII',zona:61,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0256W',nombre:'Supervisión Escolar N. 62',sector:'VIII',zona:62,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0257V',nombre:'Supervisión Escolar N. 63',sector:'VII',zona:63,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0351Z',nombre:'Supervisión Escolar N. 64',sector:'V',zona:64,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0367A',nombre:'Supervisión Escolar N. 65',sector:'II',zona:65,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FIZ0368Z',nombre:'Supervisión Escolar N. 66',sector:'IV',zona:66,tipo:'supervision',municipio:'Chicoloapan'},
  {cct:'15FIZ0369Z',nombre:'Supervisión Escolar N. 67',sector:'XI',zona:67,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0370O',nombre:'Supervisión Escolar N. 68',sector:'X',zona:68,tipo:'supervision',municipio:'Nezahualcóyotl'},
  {cct:'15FIZ0371N',nombre:'Supervisión Escolar N. 69',sector:'VIII',zona:69,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0372M',nombre:'Supervisión Escolar N. 70',sector:'I',zona:70,tipo:'supervision',municipio:'Tepetlixpa'},
  {cct:'15FIZ0373L',nombre:'Supervisión Escolar N. 71',sector:'XI',zona:71,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0374K',nombre:'Supervisión Escolar N. 72',sector:'XI',zona:72,tipo:'supervision',municipio:'Chimalhuacán'},
  {cct:'15FIZ0412X',nombre:'Supervisión Escolar N. 73',sector:'VIII',zona:73,tipo:'supervision',municipio:'Chalco'},
  {cct:'15FIZ0413W',nombre:'Supervisión Escolar N. 74',sector:'XIII',zona:74,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FIZ0414V',nombre:'Supervisión Escolar N. 75',sector:'XIII',zona:75,tipo:'supervision',municipio:'Ixtapaluca'},
  {cct:'15FJS0015D',nombre:'Supervisión General de Sector Educativo N. I',sector:'I',zona:null,tipo:'jefatura',municipio:'Amecameca'},
  {cct:'15FJS0017B',nombre:'Supervisión General de Sector Educativo N. II',sector:'II',zona:null,tipo:'jefatura',municipio:'Ixtapaluca'},
  {cct:'15FJS0016C',nombre:'Supervisión General de Sector Educativo N. III',sector:'III',zona:null,tipo:'jefatura',municipio:'Texcoco'},
  {cct:'15FJS0014E',nombre:'Supervisión General de Sector Educativo N. IV',sector:'IV',zona:null,tipo:'jefatura',municipio:'La Paz'},
  {cct:'15FJS0018A',nombre:'Supervisión General de Sector Educativo N. V',sector:'V',zona:null,tipo:'jefatura',municipio:'Nezahualcóyotl'},
  {cct:'15FJS0019Z',nombre:'Supervisión General de Sector Educativo N. VI',sector:'VI',zona:null,tipo:'jefatura',municipio:'Nezahualcóyotl'},
  {cct:'15FJS0020P',nombre:'Supervisión General de Sector Educativo N. VII',sector:'VII',zona:null,tipo:'jefatura',municipio:'Nezahualcóyotl'},
  {cct:'15FJS0047W',nombre:'Supervisión General de Sector Educativo N. VIII',sector:'VIII',zona:null,tipo:'jefatura',municipio:'Chalco'},
  {cct:'15FJS0037P',nombre:'Supervisión General de Sector Educativo N. IX',sector:'IX',zona:null,tipo:'jefatura',municipio:'Nezahualcóyotl'},
  {cct:'15FJS0038O',nombre:'Supervisión General de Sector Educativo N. X',sector:'X',zona:null,tipo:'jefatura',municipio:'Nezahualcóyotl'},
  {cct:'15FJS0039N',nombre:'Supervisión General de Sector Educativo N. XI',sector:'XI',zona:null,tipo:'jefatura',municipio:'Chimalhuacán'},
  {cct:'15FJS0050J',nombre:'Supervisión General de Sector Educativo N. XII',sector:'XII',zona:null,tipo:'jefatura',municipio:'Nezahualcóyotl'},
  {cct:'15FJS0051I',nombre:'Supervisión General de Sector Educativo N. XIII',sector:'XIII',zona:null,tipo:'jefatura',municipio:'Ixtapaluca'},
  {cct:'15ADG0086N',nombre:'Subdirección de Educación Primaria en la Región de Nezahualcóyotl',sector:'SEPRN',zona:null,tipo:'subdireccion',municipio:'Nezahualcóyotl'}
];

function buscarCCT(cctInput) {
  const q = cctInput.trim().toUpperCase();
  return CCT_DB.find(r => r.cct.toUpperCase() === q) || null;
}

function sugerirCCT(cctInput, limite = 8) {
  const q = cctInput.trim().toUpperCase();
  if (q.length < 3) return [];
  return CCT_DB.filter(r => r.cct.toUpperCase().startsWith(q)).slice(0, limite);
}

// Regla de dominio de correo institucional — verificada en vivo contra
// SIGEE (consultar_cuentas.php) el 2026-08-05 con un CCT de cada `tipo`:
//   - supervision / jefatura / subdireccion → siempre @dee.edu.mx,
//     sin importar personal/oficina.
//   - escuela → depende de tipoCuenta: "oficina" (una por escuela,
//     representa al CT/directivo) → @dee.edu.mx; "personal" (cualquier
//     docente/PAAE/ATP de esa escuela) → @aulamexiquense.mx.
// Devuelve null si el CCT no está en la base (fallback manual, sin
// forma de auto-derivar el dominio).
function otdeDominioParaCCT(cct, tipoCuenta) {
  const registro = buscarCCT(cct);
  if (!registro) return null;
  if (registro.tipo !== 'escuela') return 'dee.edu.mx';
  return tipoCuenta === 'oficina' ? 'dee.edu.mx' : 'aulamexiquense.mx';
}